name: Daily Sign In/Out

on:
  schedule:
    - cron: "0 1 * * *" # UTC 1:00 (北京时间 9:00)
    - cron: "0 10 * * *" # UTC 10:00 (北京时间 18:00)
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run sign in/out script
        run: |
          HOUR=$(TZ='Asia/Shanghai' date +%H)
          if [[ $HOUR == "09" ]]; then
            node index.js in
          elif [[ $HOUR == "18" ]]; then
            node index.js out
          else
            echo "不在签到/签退时间范围内"
          fi
        env:
          TZ: Asia/Shanghai
          XYB_CONFIG: ${{ secrets.XYB_CONFIG }}
